version: 2
jobs:
  build:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run: brew cask install firefox google-chrome
      - run: node --version
      - run: npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run test
